"""Create  tables

Revision ID: eb046eb3f664
Revises: 3f73fa297f40
Create Date: 2023-08-01 08:56:59.796812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb046eb3f664'
down_revision = '3f73fa297f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirm_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirm_password', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
